package localdns

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"sync"
	"testing"
)

func testConfig(t *testing.T) Config {
	t.Helper()
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	toolDir := t.TempDir()
	for _, tool := range []string{"caddy", "dnsmasq"} {
		if err := os.WriteFile(filepath.Join(toolDir, tool), []byte("#!/bin/sh\nexit 0\n"), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	t.Setenv("PATH", toolDir)
	return Config{Enabled: true, Domain: "HWT.Test."}
}

func directories(t *testing.T, names ...string) []string {
	t.Helper()
	root := t.TempDir()
	result := make([]string, len(names))
	for index, name := range names {
		result[index] = filepath.Join(root, name)
		if err := os.MkdirAll(result[index], 0o700); err != nil {
			t.Fatal(err)
		}
	}
	return result
}

func register(t *testing.T, cfg Config, repository, worktree string, services map[string]int) Result {
	t.Helper()
	result, err := Register(cfg, Registration{Repository: repository, Worktree: worktree, Services: services})
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func TestSanitizeAndHostnameDeterminism(t *testing.T) {
	if got := sanitize("  My_REPO...Name  ", "repo"); got != "my-repo-name" {
		t.Fatalf("sanitize = %q", got)
	}
	if got := sanitize("日本語", "repo"); got != "repo" {
		t.Fatalf("fallback = %q", got)
	}
	paths := directories(t, "Repository With A Very Long Name That Keeps Going 123456789", "Feature/API")
	host := baseHostname(paths[0], paths[1], "hwt.test")
	if host != baseHostname(paths[0], paths[1], "hwt.test") {
		t.Fatal("hostname is not deterministic")
	}
	label := strings.Split(host, ".")[0]
	if len(label) > 63 || !strings.HasSuffix(host, ".hwt.test") {
		t.Fatalf("invalid hostname %q", host)
	}
	digest := sha256.Sum256([]byte(paths[0] + "\x00" + paths[1]))
	if !strings.HasSuffix(label, "-"+hex.EncodeToString(digest[:])[:12]) {
		t.Fatalf("hostname %q lacks expected path digest", host)
	}
	other := directories(t, "Feature/API")[0]
	if baseHostname(paths[0], other, "hwt.test") == host {
		t.Fatal("distinct canonical paths produced the same hostname")
	}
}

func TestHostnameCanonicalizesExistingPaths(t *testing.T) {
	dirs := directories(t, "Repo Name", "Work Tree")
	aliasRoot := t.TempDir()
	repositoryAlias := filepath.Join(aliasRoot, "repository")
	worktreeAlias := filepath.Join(aliasRoot, "worktree")
	if err := os.Symlink(dirs[0], repositoryAlias); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(dirs[1], worktreeAlias); err != nil {
		t.Fatal(err)
	}

	got, err := Hostname(repositoryAlias, worktreeAlias, "HWT.Test.")
	if err != nil {
		t.Fatal(err)
	}
	repository, _ := filepath.EvalSymlinks(dirs[0])
	worktree, _ := filepath.EvalSymlinks(dirs[1])
	want := baseHostname(repository, worktree, "hwt.test")
	if got != want {
		t.Fatalf("Hostname() = %q, want %q", got, want)
	}
	if _, err := Hostname(repositoryAlias, filepath.Join(aliasRoot, "missing"), "hwt.test"); err == nil || !strings.Contains(err.Error(), "canonicalize worktree") {
		t.Fatalf("missing worktree error = %v", err)
	}
	if _, err := Hostname(repositoryAlias, worktreeAlias, "localhost"); err == nil || !strings.Contains(err.Error(), "invalid") {
		t.Fatalf("invalid domain error = %v", err)
	}
	if _, err := Hostname(repositoryAlias, worktreeAlias, "single"); err == nil || !strings.Contains(err.Error(), "two labels") {
		t.Fatalf("single-label domain error = %v", err)
	}
}

func TestSetupGenerationStatusAndModes(t *testing.T) {
	cfg := testConfig(t)
	setup, err := Setup(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(setup.DNSMasqInclude, setup.Paths.DNSMasq) || !strings.Contains(setup.CaddyImport, setup.Paths.Caddyfile) {
		t.Fatalf("setup guidance does not contain generated paths: %#v", setup)
	}
	if filepath.Base(filepath.Dir(setup.Paths.StateDir)) != "hwt" || filepath.Base(setup.Paths.StateDir) != "local-dns" {
		t.Fatalf("state directory does not match documented hwt/local-dns layout: %s", setup.Paths.StateDir)
	}
	dnsmasq, err := os.ReadFile(setup.Paths.DNSMasq)
	if err != nil {
		t.Fatal(err)
	}
	if string(dnsmasq) != "# Generated by hwt. Do not edit.\naddress=/.hwt.test/127.0.0.1\n" {
		t.Fatalf("dnsmasq = %q", dnsmasq)
	}
	for _, path := range []string{setup.Paths.Registry, setup.Paths.DNSMasq, setup.Paths.Caddyfile} {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatal(err)
		}
		if info.Mode().Perm() != 0o600 {
			t.Fatalf("%s mode = %o", path, info.Mode().Perm())
		}
	}
	status, err := Status(cfg)
	if err != nil || len(status.Entries) != 0 {
		t.Fatalf("status = %#v, %v", status, err)
	}
}

func TestRegisterGeneratesStableSortedConfiguration(t *testing.T) {
	cfg := testConfig(t)
	paths := directories(t, "Repo_Name", "Work Tree")
	result := register(t, cfg, paths[0], paths[1], map[string]int{"Web UI": 4000, "api": 3000})
	if result.Hostname == "" || result.URLs["Web UI"] != "http://web-ui."+result.Hostname {
		t.Fatalf("result = %#v", result)
	}
	caddy, err := os.ReadFile(result.Paths.Caddyfile)
	if err != nil {
		t.Fatal(err)
	}
	want := fmt.Sprintf("# Generated by hwt. Do not edit.\nhttp://api.%s {\n\treverse_proxy 127.0.0.1:3000\n}\n\nhttp://web-ui.%s {\n\treverse_proxy 127.0.0.1:4000\n}\n\n", result.Hostname, result.Hostname)
	if string(caddy) != want {
		t.Fatalf("Caddyfile:\n%s\nwant:\n%s", caddy, want)
	}
	first, _ := os.ReadFile(result.Paths.Registry)
	register(t, cfg, paths[0], paths[1], map[string]int{"api": 3000, "Web UI": 4000})
	second, _ := os.ReadFile(result.Paths.Registry)
	if !reflect.DeepEqual(first, second) {
		t.Fatal("idempotent registration changed registry bytes")
	}
}

func TestConcurrentRegistrationDoesNotLoseEntries(t *testing.T) {
	cfg := testConfig(t)
	repository := directories(t, "repo")[0]
	root := t.TempDir()
	const count = 16
	var wait sync.WaitGroup
	errors := make(chan error, count)
	for index := range count {
		worktree := filepath.Join(root, fmt.Sprintf("work-%02d", index))
		if err := os.Mkdir(worktree, 0o700); err != nil {
			t.Fatal(err)
		}
		wait.Add(1)
		go func() {
			defer wait.Done()
			_, err := Register(cfg, Registration{Repository: repository, Worktree: worktree, Services: map[string]int{"web": 8000}})
			errors <- err
		}()
	}
	wait.Wait()
	close(errors)
	for err := range errors {
		if err != nil {
			t.Fatal(err)
		}
	}
	status, err := Status(cfg)
	if err != nil || len(status.Entries) != count {
		t.Fatalf("got %d registrations: %v", len(status.Entries), err)
	}
}

func TestServiceValidationAndSanitizedCollision(t *testing.T) {
	cfg := testConfig(t)
	paths := directories(t, "repo", "work")
	tests := []struct {
		services map[string]int
		want     string
	}{
		{nil, "at least one"},
		{map[string]int{"api": 0}, "port"},
		{map[string]int{"API": 1, "api": 2}, "conflicts"},
		{map[string]int{"日本語": 1}, "valid DNS label"},
	}
	for _, test := range tests {
		_, err := Register(cfg, Registration{Repository: paths[0], Worktree: paths[1], Services: test.services})
		if err == nil || !strings.Contains(err.Error(), test.want) {
			t.Fatalf("error = %v, want %q", err, test.want)
		}
	}
}

func TestHostnameOwnershipConflict(t *testing.T) {
	cfg := testConfig(t)
	dirs := directories(t, "repo", "owner", "challenger")
	setup, err := Setup(cfg)
	if err != nil {
		t.Fatal(err)
	}
	owner, _ := canonicalPath(dirs[1], "worktree")
	repository, _ := canonicalPath(dirs[0], "repository")
	challenger, _ := canonicalPath(dirs[2], "worktree")
	host := baseHostname(repository, challenger, "hwt.test")
	registry := registryFile{Entries: map[string]Entry{owner: {Worktree: owner, Repository: repository, Domain: "hwt.test", Hostname: host, Services: map[string]int{"web": 80}}}}
	data, _ := json.MarshalIndent(registry, "", "  ")
	data = append(data, '\n')
	if err := os.WriteFile(setup.Paths.Registry, data, 0o600); err != nil {
		t.Fatal(err)
	}
	_, err = Register(cfg, Registration{Repository: dirs[0], Worktree: dirs[2], Services: map[string]int{"web": 80}})
	if err == nil || !strings.Contains(err.Error(), "already registered") {
		t.Fatalf("error = %v", err)
	}
}

func TestCanonicalSymlinksAndExactReleaseBoundary(t *testing.T) {
	cfg := testConfig(t)
	dirs := directories(t, "repo", "work", "work-extra")
	alias := filepath.Join(t.TempDir(), "alias")
	if err := os.Symlink(dirs[1], alias); err != nil {
		t.Fatal(err)
	}
	result := register(t, cfg, dirs[0], alias, map[string]int{"web": 80})
	status, _ := Status(cfg)
	canonicalWorktree, _ := filepath.EvalSymlinks(dirs[1])
	if status.Entries[0].Worktree != canonicalWorktree {
		t.Fatalf("path was not canonicalized: %q", status.Entries[0].Worktree)
	}
	register(t, cfg, dirs[0], dirs[2], map[string]int{"web": 81})
	if err := Release(dirs[1], cfg); err != nil {
		t.Fatal(err)
	}
	status, _ = Status(cfg)
	canonicalOther, _ := filepath.EvalSymlinks(dirs[2])
	if len(status.Entries) != 1 || status.Entries[0].Worktree != canonicalOther {
		t.Fatalf("release crossed path boundary: %#v (%s)", status.Entries, result.Hostname)
	}
}

func TestReleaseAcceptsRemovedCanonicalWorktree(t *testing.T) {
	cfg := testConfig(t)
	dirs := directories(t, "repo", "work")
	register(t, cfg, dirs[0], dirs[1], map[string]int{"web": 80})
	canonical, err := filepath.EvalSymlinks(dirs[1])
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(dirs[1]); err != nil {
		t.Fatal(err)
	}
	if err := Release(canonical, cfg); err != nil {
		t.Fatalf("release removed worktree: %v", err)
	}
	status, err := Status(cfg)
	if err != nil || len(status.Entries) != 0 {
		t.Fatalf("registration remains after release: %#v, %v", status.Entries, err)
	}
	if err := Release("relative/worktree", cfg); err == nil || !strings.Contains(err.Error(), "canonical absolute") {
		t.Fatalf("relative release error = %v", err)
	}
	_, err = Register(cfg, Registration{Repository: dirs[0], Worktree: canonical, Services: map[string]int{"web": 80}})
	if err == nil || !strings.Contains(err.Error(), "canonicalize worktree") {
		t.Fatalf("registration accepted removed worktree: %v", err)
	}
}

func TestSetupReportsMissingRequiredTools(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	t.Setenv("PATH", t.TempDir())
	_, err := Setup(Config{Enabled: true, Domain: "hwt.test"})
	if err == nil || !strings.Contains(err.Error(), "caddy, dnsmasq") || !strings.Contains(err.Error(), "does not install") {
		t.Fatalf("missing tools error = %v", err)
	}

	toolDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(toolDir, "caddy"), []byte("#!/bin/sh\nexit 0\n"), 0o700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", toolDir)
	_, err = Setup(Config{Enabled: true, Domain: "hwt.test"})
	if err == nil || strings.Contains(err.Error(), "caddy,") || !strings.Contains(err.Error(), "dnsmasq") {
		t.Fatalf("single missing tool error = %v", err)
	}
}

func stub(t *testing.T, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "reload")
	if err := os.WriteFile(path, []byte("#!/bin/sh\n"+body+"\n"), 0o700); err != nil {
		t.Fatal(err)
	}
	return path
}

func snapshots(t *testing.T, paths Paths) map[string][]byte {
	t.Helper()
	result := map[string][]byte{}
	for _, path := range []string{paths.Registry, paths.DNSMasq, paths.Caddyfile} {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		result[path] = data
	}
	return result
}

func TestReloadPlaceholdersAndIdempotency(t *testing.T) {
	cfg := testConfig(t)
	marker := filepath.Join(t.TempDir(), "calls")
	cfg.Reload = []string{stub(t, `printf '%s\n' "$@" >> "$4"`), "{caddyfile}", "{dnsmasq}", "{state_dir}", marker}
	setup, err := Setup(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Setup(cfg); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(marker)
	lines := strings.Split(strings.TrimSpace(string(data)), "\n")
	if !reflect.DeepEqual(lines, []string{setup.Paths.Caddyfile, setup.Paths.DNSMasq, setup.Paths.StateDir, marker}) {
		t.Fatalf("reload argv = %#v", lines)
	}
}

func TestReloadFailuresRestoreExactState(t *testing.T) {
	cfg := testConfig(t)
	setup, err := Setup(cfg)
	if err != nil {
		t.Fatal(err)
	}
	before := snapshots(t, setup.Paths)
	dirs := directories(t, "repo", "work")
	cfg.Reload = []string{stub(t, `echo 'reload exploded' >&2; exit 23`)}
	_, err = Register(cfg, Registration{Repository: dirs[0], Worktree: dirs[1], Services: map[string]int{"web": 80}})
	if err == nil || !strings.Contains(err.Error(), "reload exploded") {
		t.Fatalf("error = %v", err)
	}
	for path, want := range before {
		got, _ := os.ReadFile(path)
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("%s was not restored exactly", path)
		}
	}
	cfg.Reload = []string{filepath.Join(t.TempDir(), "missing")}
	_, err = Register(cfg, Registration{Repository: dirs[0], Worktree: dirs[1], Services: map[string]int{"web": 80}})
	if err == nil || !strings.Contains(err.Error(), "was not found") {
		t.Fatalf("missing executable error = %v", err)
	}
}

func TestFailedInitialSetupRestoresAbsence(t *testing.T) {
	cfg := testConfig(t)
	cfg.Reload = []string{stub(t, "exit 1")}
	_, err := Setup(cfg)
	if err == nil {
		t.Fatal("setup succeeded despite failed reload")
	}
	paths, _, prepareErr := prepare(cfg, false)
	if prepareErr != nil {
		t.Fatal(prepareErr)
	}
	for _, path := range []string{paths.Registry, paths.DNSMasq, paths.Caddyfile} {
		if _, statErr := os.Stat(path); !os.IsNotExist(statErr) {
			t.Fatalf("failed setup left owned file %s", path)
		}
	}
}

func TestReleaseAndTeardownRollback(t *testing.T) {
	cfg := testConfig(t)
	dirs := directories(t, "repo", "work")
	result := register(t, cfg, dirs[0], dirs[1], map[string]int{"web": 80})
	before := snapshots(t, result.Paths)
	failing := stub(t, "exit 1")
	cfg.Reload = []string{failing}
	if err := Release(dirs[1], cfg); err == nil {
		t.Fatal("release succeeded despite failed reload")
	}
	for path, want := range before {
		got, _ := os.ReadFile(path)
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("release did not restore %s", path)
		}
	}
	if err := Teardown(Config{Enabled: true, Domain: cfg.Domain}, false); err == nil || !strings.Contains(err.Error(), "refusing") {
		t.Fatalf("teardown error = %v", err)
	}
	if err := Teardown(cfg, true); err == nil {
		t.Fatal("teardown succeeded despite failed reload")
	}
	for path, want := range before {
		got, _ := os.ReadFile(path)
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("teardown did not restore %s", path)
		}
	}
	if err := Teardown(Config{Enabled: true, Domain: cfg.Domain}, true); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{result.Paths.Registry, result.Paths.DNSMasq, result.Paths.Caddyfile} {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("owned file remains: %s", path)
		}
	}
}

func TestStatusHasNoSideEffects(t *testing.T) {
	root := t.TempDir()
	t.Setenv("XDG_STATE_HOME", root)
	status, err := Status(Config{Domain: "hwt.test"})
	if err != nil || len(status.Entries) != 0 {
		t.Fatalf("status = %#v, %v", status, err)
	}
	entries, err := os.ReadDir(root)
	if err != nil || len(entries) != 0 {
		t.Fatalf("status created state: %#v, %v", entries, err)
	}
	if err := Teardown(Config{Domain: "hwt.test"}, false); err != nil {
		t.Fatal(err)
	}
}

func TestValidationAndUnsupportedOS(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	invalid := []string{"", "localhost", "foo/bar", "bad_label.test", "-bad.test", strings.Repeat("a", 190)}
	for _, domain := range invalid {
		if _, err := Setup(Config{Enabled: true, Domain: domain}); err == nil {
			t.Fatalf("accepted domain %q", domain)
		}
	}
	if _, err := Setup(Config{Domain: "hwt.test"}); err == nil || !strings.Contains(err.Error(), "disabled") {
		t.Fatalf("disabled error = %v", err)
	}
	original := currentGOOS
	currentGOOS = func() string { return "windows" }
	t.Cleanup(func() { currentGOOS = original })
	_, err := Setup(Config{Enabled: true, Domain: "hwt.test"})
	if err == nil || !strings.Contains(err.Error(), "only darwin and linux") {
		t.Fatalf("unsupported error = %v", err)
	}
}

func TestStatusSortsEntries(t *testing.T) {
	cfg := testConfig(t)
	dirs := directories(t, "repo", "z", "a")
	register(t, cfg, dirs[0], dirs[1], map[string]int{"web": 80})
	register(t, cfg, dirs[0], dirs[2], map[string]int{"web": 80})
	status, err := Status(cfg)
	if err != nil {
		t.Fatal(err)
	}
	got := []string{status.Entries[0].Worktree, status.Entries[1].Worktree}
	want := append([]string(nil), got...)
	sort.Strings(want)
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("entries are not sorted: %#v", got)
	}
}
